# Generated by Django 5.0.1 on 2024-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descuento',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_descuento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
