# Generated by Django 5.0.1 on 2024-02-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_categoria_descuento_categoria_fecha_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_descuento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
