# Generated by Django 5.0.1 on 2024-02-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_categoria_descuento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='fecha_descuento',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
