# Generated by Django 5.0.1 on 2024-02-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_fecha_descuento_categoria_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
    ]
