# Generated by Django 5.0.1 on 2024-02-22 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_valoraciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoraciones',
            name='actualizado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='valoraciones',
            name='creado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
