# Generated by Django 5.0.2 on 2024-02-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_valoraciones_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
