# Generated by Django 5.0.1 on 2024-01-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_rename_personal_cuenta_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='administrador',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='super_administrador',
            new_name='is_superadmin',
        ),
    ]
