# Generated by Django 5.0.1 on 2024-01-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_rename_activo_cuenta_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='username',
        ),
    ]
