# Generated by Django 5.0.1 on 2024-01-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_rename_inicio_acceso_cuenta_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
