# Generated by Django 5.0.1 on 2024-01-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_rename_is_superadmin_cuenta_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='email',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='date_joined',
            new_name='inicio_acceso',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='is_superuser',
            new_name='is_superadmin',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cuenta',
            old_name='phone',
            new_name='telefono',
        ),
    ]
