# Generated by Django 5.0.1 on 2024-01-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_rename_username_cuenta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='usuario',
            new_name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actvio'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='Super Administrador'),
        ),
    ]
