# Generated by Django 5.0.1 on 2024-01-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_rename_usuario_cuenta_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='nombre_usuario',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
