# Generated by Django 5.0.1 on 2024-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_rename_nombre_usuario_cuenta_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='usuario'),
        ),
    ]
