# Generated by Django 5.0.1 on 2024-02-08 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0011_alter_cuenta_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='inicio_acceso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='ultimo_acceso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
