# Generated by Django 5.0.2 on 2024-03-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0013_remove_cuenta_is_staff_remove_cuenta_is_superadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='is_user',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='usuario'),
        ),
    ]
