# Generated by Django 5.0.2 on 2024-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0014_remove_cuenta_is_user_cuenta_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='Super Administrador'),
        ),
    ]
