# Generated by Django 5.0.2 on 2024-03-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0015_cuenta_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='is_superadmin',
        ),
    ]
