# Generated by Django 5.0.2 on 2024-03-15 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0017_rename_is_admin_cuenta_is_superadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='is_superadmin',
            new_name='is_admin',
        ),
    ]
