# Generated by Django 5.0.2 on 2024-03-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0018_rename_is_superadmin_cuenta_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Actvio'),
        ),
    ]
