# Generated by Django 5.0.1 on 2024-01-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='carrito_sesion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
