# Generated by Django 5.0.1 on 2024-01-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_carrito_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
