# Generated by Django 5.0.1 on 2024-01-28 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_carrito_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_session', models.CharField(blank=True, max_length=250)),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='carrito_sesion',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='carrito',
            name='carritoSesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carritosesion'),
        ),
    ]
