# Generated by Django 5.0.1 on 2024-02-07 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='correo_elctronico',
            new_name='correo_electronico',
        ),
    ]
