# Generated by Django 5.0.1 on 2024-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_rename_correo_elctronico_pedido_correo_electronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='correo_electronico',
            field=models.EmailField(max_length=100),
        ),
    ]
