# Generated by Django 5.0.1 on 2024-02-12 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_correo_electronico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='estado',
            new_name='estado_pago',
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(choices=[('Leticia', 'Leticia'), ('Medellin', 'Medellin'), ('Neiva', 'Neiva')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='departamento',
            field=models.CharField(choices=[('Amazonas', 'Amazonas'), ('Antioquía', 'Antioquía'), ('Huila', 'Huila')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_local',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
