# Generated by Django 5.0.1 on 2024-02-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(upload_to='comprobante_pago/'),
        ),
    ]
