# Generated by Django 5.0.1 on 2024-02-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_alter_pago_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
    ]
