# Generated by Django 5.0.1 on 2024-02-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_pago_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pago_id',
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_envio',
            field=models.CharField(choices=[('En espera de pago', 'En espera de pago'), ('Enviado', 'Enviado'), ('Rechazado', 'Rechazado')], default='En espera de pago', max_length=50),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado_pago',
            field=models.CharField(choices=[('Verificacion', 'Verificacion'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Verificacion', max_length=50),
        ),
    ]
