# Generated by Django 5.0.1 on 2024-02-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_remove_pago_pago_id_pago_estado_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cantidad_pagada',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
