# Generated by Django 5.0.1 on 2024-02-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_alter_pago_cantidad_pagada_alter_pedido_total_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoProducto',
        ),
    ]
