# Generated by Django 5.0.2 on 2024-03-17 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_alter_pago_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(upload_to='comprobantes/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
