# Generated by Django 5.0.2 on 2024-03-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_alter_pago_cantidad_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
